<div id="jsoneditor" style="width: 100%; height: 700px;"></div>
<button id="selectPath">Select</button>
<script>
    require([
        'jquery',
        'Ecomteck_OrderCustomAttributes/js/lib/jsoneditor/jsoneditor'
    ], function($,JSONEditor) {
        // create the editor
        var container = document.getElementById("jsoneditor");
        var options = {
        };
        var editor = new JSONEditor(container, options);

        // set json
        var json = <?= /* @escapeNotVerified */ $block->getJsLayout() ?>;
        editor.set(json);
        $('#selectPath').click(function(){
            var paths = [];
            $('.jsoneditor-treepath-element').each(function(index){
                if(index > 0){
                    paths.push($(this).text());
                }
            });
            console.log(paths.join('/'));
        });
    })
</script>